name: cron

on:
  workflow_dispatch:
    # inputs:
    #   steps:
    #     type: choice
    #     options:
    #       - archive-pages
    #       - cleanup-images
    #       - cleanup-commits
    #       - push-web-archive
  schedule:
    # Runs at midnigth
    - cron: "0 0 * * *"
    # Runs every 1 hour
    - cron: "0 */1 * * *"

jobs:
  cron:
    if: github.repository == 'MajorDigest/majordigest.github.io'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        # with:
        #   ref: gh-pages

      - name: Archive Pages 🗄️
        if: github.event.schedule == '0 0 * * *' || github.event_name == 'workflow_dispatch'
        run: |
          export ARCHIVE_DATE="$(TZ=America/New_York date '+%Y/%m/%d')"
          export LAST_MODIFIED="$(TZ=America/New_York date '+%Y-%m-%d')"
          export ARCHIVE_PATH="archive/${ARCHIVE_DATE}"
          export IMAGE_TIMESTAMP="$(TZ=America/New_York date '+%Y%m%d')"
          export IMAGE_SRC_PATTERN="src=\"/assets/images/"
          export IMAGE_REPLACEMENT="src=\"https://web.archive.org/web/${IMAGE_TIMESTAMP}im_/https://majordigest.com/assets/images/"
          export CANONICAL_URL_PATTERN="=\"https://majordigest.com/\">"
          export CANONICAL_REPLACEMENT="=\"https://majordigest.com/${ARCHIVE_PATH}/\">"
          export ARCHIVE_LINK_PLACEHOLDER="<!--archive-->"
          export ARCHIVE_LINK_TEXT="$(TZ=America/New_York date '+%B %-d, %Y')"
          export ARCHIVE_LINK="${ARCHIVE_LINK_PLACEHOLDER}\n<a href=\"/${ARCHIVE_PATH}/\" title=\"News archive of ${ARCHIVE_LINK_TEXT}\">${ARCHIVE_LINK_TEXT}</a>"
          export SITEMAP_LINK="${ARCHIVE_LINK_PLACEHOLDER}\n<url><loc>https://majordigest.com/${ARCHIVE_PATH}/</loc><lastmod>${LAST_MODIFIED}</lastmod><changefreq>never</changefreq></url>"
          export PRECONNECT_PLACEHOLDER="</head>"
          export PRECONNECT_REPLACEMENT="<link rel=\"preconnect\" href=\"https://web.archive.org/\"></head>"
          echo "ARCHIVE_PATH: ${ARCHIVE_PATH}"
          mkdir -p "${ARCHIVE_PATH}"
          cp index.html "${ARCHIVE_PATH}"
          sed -i -e "s#$IMAGE_SRC_PATTERN#$IMAGE_REPLACEMENT#g" "${ARCHIVE_PATH}/index.html"
          sed -i -e "s#$CANONICAL_URL_PATTERN#$CANONICAL_REPLACEMENT#g" "${ARCHIVE_PATH}/index.html"
          sed -i -e "s#$PRECONNECT_PLACEHOLDER#$PRECONNECT_REPLACEMENT#g" "${ARCHIVE_PATH}/index.html"
          sed -i -e "s#$ARCHIVE_LINK_PLACEHOLDER#$ARCHIVE_LINK#g" "archive/index.html"
          sed -i -e "s#$ARCHIVE_LINK_PLACEHOLDER#$SITEMAP_LINK#g" "archive/sitemap.xml"
          git config --global user.name 'Valentin Podkamennyi'
          git config --global user.email 'vpodk@users.noreply.github.com'
          git add -A
          git commit -m "Added archive for ${ARCHIVE_DATE}" && git push
          curl --silent "https://www.google.com/ping?sitemap=https://majordigest.com/archive/sitemap.xml"

      - name: Cleanup Images 🧹
        if: github.event.schedule == '0 0 * * *' || github.event_name == 'workflow_dispatch'
        run: |
          export LAST_MONTH="$(date -d 'last month' '+%Y/%m')"
          export DIRS=( news politics sports tech us world )
          for dir in "${DIRS[@]}"; do rm -rf "assets/images/$dir/${LAST_MONTH}"; done
          git add -A
          git status
          echo "diff exit-code: $(git diff --exit-code)"
          git diff --exit-code || git commit -m "Clean up for ${LAST_MONTH}" && git push

      - name: Cleanup Commits 🧹
        if: github.event.schedule == '0 0 * * *' || github.event_name == 'workflow_dispatch'
        run: |
          export LAST_COMMIT="$(git rev-parse HEAD)"
          export TEMP_BRANCH="temp$RANDOM"
          git config --global user.name 'Valentin Podkamennyi'
          git config --global user.email 'vpodk@users.noreply.github.com'
          echo "[DEBUG] Run checkout:"
          git checkout --orphan $TEMP_BRANCH $LAST_COMMIT
          echo "[DEBUG] Run commit:"
          git commit --allow-empty -m "Truncated history"
          echo "[DEBUG] Run rebase:"
          git rebase --onto $TEMP_BRANCH $LAST_COMMIT main
          echo "[DEBUG] Delete $TEMP_BRANCH branch:"
          git branch -D $TEMP_BRANCH
          echo "[DEBUG] Delete all the objects w/o references:"
          git prune --progress
          echo "[DEBUG] Run git status:"
          git status
          echo "[DEBUG] Run git push:"
          git push -f
        # echo "[DEBUG] Run aggressively collect garbage:"
        # git gc --aggressive

      - name: Push Web Archive 🕸️
        if: github.event.schedule == '0 */1 * * *' || github.event_name == 'workflow_dispatch'
        run: |
          echo -n "Status (home): " && curl -o /dev/null -w "%{http_code}\\n" \
            --data "url=https%3A%2F%2Fmajordigest.com%2F&capture_all=on" \
            -X POST https://web.archive.org/save/https://majordigest.com/
          export PAGES=( tech us world politics sports )
          for page in "${PAGES[@]}"; do
            echo -n "Status ($page): " && curl -o /dev/null -w "%{http_code}\\n" \
              --data "url=https%3A%2F%2Fmajordigest.com%2F$page%2F&capture_all=on" \
              -X POST https://web.archive.org/save/https://majordigest.com/$page/
          done
